In [1]:
import pandas as pd
import sqlite3 as sql

C:\Users\kk\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
conn = sql.connect('database.sqlite')
conn

In [3]:
pd.read_sql_query('select * from sqlite_master', conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [4]:
pd.read_sql_query('select * from salaries', conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [5]:
pd.read_sql_query('select * from Salaries where employeeName is null',conn)

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

In [6]:
pd.read_sql_query('select * from Salaries where employeeName is not null', conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [7]:
pd.read_sql_query('select * from Salaries where employeeName not null', conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [8]:
pd.read_sql_query('select employeeName , Jobtitle, totalpay from salaries',conn)

,EmployeeName,JobTitle,TotalPay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,9999999.00
1,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
2,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
3,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19
4,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,316285.74
...,...,...,...
148648,Roy I Tillery,Custodian,0.00
148649,Not provided,Not provided,0.00
148650,Not provided,Not provided,0.00
148651,Not provided,Not provided,0.00
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13

In [9]:
pd.read_sql_query('select employeeName , Jobtitle, totalpay from salaries where employeename is null',conn)

Empty DataFrame
Columns: [EmployeeName, JobTitle, TotalPay]
Index: []

In [10]:
pd.read_sql_query('select employeeName , Jobtitle, totalpay from salaries where employeename not null',conn)

,EmployeeName,JobTitle,TotalPay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,9999999.00
1,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
2,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
3,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19
4,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,316285.74
...,...,...,...
148648,Roy I Tillery,Custodian,0.00
148649,Not provided,Not provided,0.00
148650,Not provided,Not provided,0.00
148651,Not provided,Not provided,0.00
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13

In [11]:
pd.read_sql_query('select distinct JObtitle from Salaries', conn)

                                            JobTitle
0     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                    CAPTAIN III (POLICE DEPARTMENT)
2               WIRE ROPE CABLE MAINTENANCE MECHANIC
3       DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
4                          ASSISTANT DEPUTY CHIEF II
...                                              ...
2154                    Sr Cnselor, Juv Hall (SFERS)
2155                  Forensic Toxicologist Supervis
2156                                      Conversion
2157                                       Cashier 3
2158                                    Not provided

[2159 rows x 1 columns]

In [12]:
pd.read_sql_query('select distinct(JObtitle) from Salaries', conn)

                                            JobTitle
0     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                    CAPTAIN III (POLICE DEPARTMENT)
2               WIRE ROPE CABLE MAINTENANCE MECHANIC
3       DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
4                          ASSISTANT DEPUTY CHIEF II
...                                              ...
2154                    Sr Cnselor, Juv Hall (SFERS)
2155                  Forensic Toxicologist Supervis
2156                                      Conversion
2157                                       Cashier 3
2158                                    Not provided

[2159 rows x 1 columns]

In [13]:
pd.read_sql_query('select distinct(JObtitle) from Salaries where jobtitle != "Not provided" ', conn)

                                            JobTitle
0     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                    CAPTAIN III (POLICE DEPARTMENT)
2               WIRE ROPE CABLE MAINTENANCE MECHANIC
3       DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
4                          ASSISTANT DEPUTY CHIEF II
...                                              ...
2153                        Marina Associate Manager
2154                    Sr Cnselor, Juv Hall (SFERS)
2155                  Forensic Toxicologist Supervis
2156                                      Conversion
2157                                       Cashier 3

[2158 rows x 1 columns]

In [14]:
pd.read_sql_query('select distinct(EmployeeName) from Salaries where EmployeeName != "Not provided" ', conn)

              EmployeeName
0           NATHANIEL FORD
1           ALBERT PARDINI
2        CHRISTOPHER CHONG
3          PATRICK GARDNER
4           DAVID SULLIVAN
...                    ...
110804   Afakasi O Afakasi
110805      Kenneth Mackey
110806      Mark W Mcclure
110807  Charlene D Mccully
110808           Joe Lopez

[110809 rows x 1 columns]

In [15]:
pd.read_sql_query('select distinct(JObtitle) from Salaries where jobtitle != "not provided" ', conn)

                                            JobTitle
0     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                    CAPTAIN III (POLICE DEPARTMENT)
2               WIRE ROPE CABLE MAINTENANCE MECHANIC
3       DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
4                          ASSISTANT DEPUTY CHIEF II
...                                              ...
2154                    Sr Cnselor, Juv Hall (SFERS)
2155                  Forensic Toxicologist Supervis
2156                                      Conversion
2157                                       Cashier 3
2158                                    Not provided

[2159 rows x 1 columns]

In [16]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [17]:
q = '''select employeename Employee, Jobtitle Title, Totalpay Pay
    from Salaries
'''

sql_query(q)

,Employee,Title,Pay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,9999999.00
1,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
2,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
3,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19
4,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,316285.74
...,...,...,...
148648,Roy I Tillery,Custodian,0.00
148649,Not provided,Not provided,0.00
148650,Not provided,Not provided,0.00
148651,Not provided,Not provided,0.00
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13

In [18]:
q = '''select employeename Employee_Name, Jobtitle MY_Title, Totalpay mY_Pay
    from Salaries
'''

sql_query(q)

,Employee_Name,MY_Title,mY_Pay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,9999999.00
1,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
2,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
3,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19
4,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,316285.74
...,...,...,...
148648,Roy I Tillery,Custodian,0.00
148649,Not provided,Not provided,0.00
148650,Not provided,Not provided,0.00
148651,Not provided,Not provided,0.00
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13

In [19]:
q = '''select employeename 'Employee Name', Jobtitle 'MY Title', Totalpay 'mY Pay'
    from Salaries
'''

sql_query(q)

,Employee Name,MY Title,mY Pay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,9999999.00
1,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
2,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
3,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19
4,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,316285.74
...,...,...,...
148648,Roy I Tillery,Custodian,0.00
148649,Not provided,Not provided,0.00
148650,Not provided,Not provided,0.00
148651,Not provided,Not provided,0.00
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13

In [20]:
q = '''select employeename as Employee
    from Salaries
'''

sql_query(q)

                 Employee
0          NATHANIEL FORD
1          ALBERT PARDINI
2       CHRISTOPHER CHONG
3         PATRICK GARDNER
4          DAVID SULLIVAN
...                   ...
148648      Roy I Tillery
148649       Not provided
148650       Not provided
148651       Not provided
148652          Joe Lopez

[148653 rows x 1 columns]

In [21]:
q = '''select jobtitle Title, TotalPay Pay from salaries
    order by 2'''

sql_query(q)

                                                 Title         Pay
0                           Counselor, Log Cabin Ranch     -618.13
1           STATIONARY ENGINEER, WATER TREATMENT PLANT        0.00
2                                     TRANSIT OPERATOR        0.00
3                                           MANAGER IV        0.00
4                                Deputy Court Clerk II        0.00
...                                                ...         ...
148648                                       Captain 3   350403.41
148649                    Lieutenant, Fire Suppression   362844.66
148650                               Asst Med Examiner   390111.98
148651                                  Deputy Chief 3   471952.64
148652  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  9999999.00

[148653 rows x 2 columns]

In [22]:
q = '''select jobtitle Title, TotalPay Pay from salaries
    order by totalpay'''

sql_query(q)

                                                 Title         Pay
0                           Counselor, Log Cabin Ranch     -618.13
1           STATIONARY ENGINEER, WATER TREATMENT PLANT        0.00
2                                     TRANSIT OPERATOR        0.00
3                                           MANAGER IV        0.00
4                                Deputy Court Clerk II        0.00
...                                                ...         ...
148648                                       Captain 3   350403.41
148649                    Lieutenant, Fire Suppression   362844.66
148650                               Asst Med Examiner   390111.98
148651                                  Deputy Chief 3   471952.64
148652  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  9999999.00

[148653 rows x 2 columns]

In [23]:
q = '''select jobtitle Title, TotalPay Pay from salaries
    order by 2 desc'''

sql_query(q)

                                                 Title         Pay
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  9999999.00
1                                       Deputy Chief 3   471952.64
2                                    Asst Med Examiner   390111.98
3                         Lieutenant, Fire Suppression   362844.66
4                                            Captain 3   350403.41
...                                                ...         ...
148648                                       Custodian        0.00
148649                                    Not provided        0.00
148650                                    Not provided        0.00
148651                                    Not provided        0.00
148652                      Counselor, Log Cabin Ranch     -618.13

[148653 rows x 2 columns]

In [24]:
q = '''select jobtitle Title, TotalPay Pay from salaries
    where jobtitle != 'Not provided'
    order by 2 desc'''

sql_query(q)

                                                 Title         Pay
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  9999999.00
1                                       Deputy Chief 3   471952.64
2                                    Asst Med Examiner   390111.98
3                         Lieutenant, Fire Suppression   362844.66
4                                            Captain 3   350403.41
...                                                ...         ...
148644                       Human Services Technician        0.00
148645                     Communications Dispatcher 2        0.00
148646                                       Custodian        0.00
148647                                       Custodian        0.00
148648                      Counselor, Log Cabin Ranch     -618.13

[148649 rows x 2 columns]

In [25]:
q = '''select jobtitle Title, TotalPay Pay, OtherPay, BasePay as Base from salaries
    where jobtitle != 'Not provided'
    order by 4'''

sql_query(q)

                          Title    Pay  OtherPay    Base
0                  Junior Clerk  83.01      0.00 -166.01
1                  Junior Clerk  61.07      0.00 -121.63
2                  Junior Clerk  54.61      0.00 -109.22
3                  Junior Clerk  53.30      0.00  -106.6
4                  Junior Clerk  51.20      0.00 -101.88
...                         ...    ...       ...     ...
148644  PS Aide Health Services  10.67     10.67
148645             Senior Clerk   5.56      5.56
148646         Police Officer 3   0.00      0.00
148647         Police Officer 3   0.00      0.00
148648         Police Officer 3   0.00      0.00

[148649 rows x 4 columns]

In [26]:
q = '''select jobtitle Title, TotalPay Pay, OtherPay, BasePay as Base from salaries
    where jobtitle != 'Not provided'
    order by basepay'''

sql_query(q)

                          Title    Pay  OtherPay    Base
0                  Junior Clerk  83.01      0.00 -166.01
1                  Junior Clerk  61.07      0.00 -121.63
2                  Junior Clerk  54.61      0.00 -109.22
3                  Junior Clerk  53.30      0.00  -106.6
4                  Junior Clerk  51.20      0.00 -101.88
...                         ...    ...       ...     ...
148644  PS Aide Health Services  10.67     10.67
148645             Senior Clerk   5.56      5.56
148646         Police Officer 3   0.00      0.00
148647         Police Officer 3   0.00      0.00
148648         Police Officer 3   0.00      0.00

[148649 rows x 4 columns]

In [27]:
q = '''select jobtitle Title, TotalPay Pay, OtherPay, BasePay as Base from salaries
    where jobtitle != 'Not provided'
    order by base'''

sql_query(q)

                          Title    Pay  OtherPay    Base
0                  Junior Clerk  83.01      0.00 -166.01
1                  Junior Clerk  61.07      0.00 -121.63
2                  Junior Clerk  54.61      0.00 -109.22
3                  Junior Clerk  53.30      0.00  -106.6
4                  Junior Clerk  51.20      0.00 -101.88
...                         ...    ...       ...     ...
148644  PS Aide Health Services  10.67     10.67
148645             Senior Clerk   5.56      5.56
148646         Police Officer 3   0.00      0.00
148647         Police Officer 3   0.00      0.00
148648         Police Officer 3   0.00      0.00

[148649 rows x 4 columns]

In [28]:
q = '''select employeename, totalpay from salaries
    order by 2 desc limit 10'''

sql_query(q)

           EmployeeName    TotalPay
0        NATHANIEL FORD  9999999.00
1           David Shinn   471952.64
2            Amy P Hart   390111.98
3        Gary Altenberg   362844.66
4         John Goldberg   350403.41
5           Samson  Lai   347102.32
6       Ellen G Moffatt   344187.46
7  William J Coaker Jr.   339653.70
8        Gregory P Suhr   339282.07
9     Frederick Binkley   337204.86

In [29]:
q = '''select jobtitle title, overtimepay from salaries
    where overtimepay > 50000
    and 
    overtimepay != 'Not Provided'
    order by 2 desc
    limit 10'''

sql_query(q)

                          title  OvertimePay
0  Lieutenant, Fire Suppression    220909.48
1                Deputy Sheriff    196689.18
2     EMT/Paramedic/Firefighter    192424.49
3                Deputy Sheriff    173547.73
4                Deputy Sheriff    173178.23
5                Deputy Sheriff    169659.92
6  Lieutenant, Fire Suppression    163477.81
7                   Firefighter    160418.47
8                Deputy Sheriff    156077.49
9                Deputy Sheriff    148147.92

In [30]:
# Show All Employess With A Total Pay Between 50,000 and 75,000
q = '''SELECT EmployeeName, TotalPay FROM Salaries
       WHERE TotalPay >= 50000 AND TotalPay <= 75000
       ORDER BY TotalPay '''

sql_query(q)

           EmployeeName  TotalPay
0      Bernardus S Jong  50003.13
1             ALEX DURU  50003.63
2        Reanna  Albert  50005.00
3        Janice W Phung  50009.05
4          ERICK DAIGLE  50009.48
...                 ...       ...
33552  ANGELA WHITTAKER  74997.84
33553     LINDA BARNARD  74998.30
33554      Hernan Canas  74998.35
33555     HEDLEY PRINCE  74998.73
33556   MAMIKO NAKAMURA  74999.62

[33557 rows x 2 columns]

In [31]:
# Show All Employees With A BasePay less than 50,000 Or A TotalPay Greater Than 100,000
q = '''SELECT EmployeeName, BasePay, TotalPay FROM Salaries
       WHERE BasePay < 50000 OR TotalPay > 100000'''

sql_query(q)

            EmployeeName    BasePay    TotalPay
0         NATHANIEL FORD  167411.18  9999999.00
1         ALBERT PARDINI  212739.13   335279.91
2      CHRISTOPHER CHONG      77916   332343.61
3        PATRICK GARDNER   134401.6   326373.19
4         DAVID SULLIVAN     118602   316285.74
...                  ...        ...         ...
91289   Carolyn A Wilson          0        0.00
91290     Joann Anderson          0        0.00
91291        Leon Walker          0        0.00
91292      Roy I Tillery          0        0.00
91293          Joe Lopez          0     -618.13

[91294 rows x 3 columns]

#### **1. What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [51]:
q = '''SELECT JobTitle, AVG(TotalPayBenefits) as AvgTotalPayBenefits 
       FROM Salaries
       WHERE JobTitle != "Not Provided"
       And JobTitle != "Not provided"
       GROUP BY JobTitle'''

sql_query(q)

                                            JobTitle  AvgTotalPayBenefits
0                                      ACCOUNT CLERK         44035.664337
1                                         ACCOUNTANT         47429.268000
2                                  ACCOUNTANT INTERN         29031.742917
3                        ACPO,JuvP, Juv Prob (SFERS)         80266.370000
4                                      ACUPUNCTURIST         67594.400000
...                                              ...                  ...
2153                           X-RAY LABORATORY AIDE         52705.880385
2154                           X-Ray Laboratory Aide         69521.123200
2155  YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS         53632.870000
2156                              Youth Comm Advisor         60118.550000
2157                                     ZOO CURATOR         66686.560000

[2158 rows x 2 columns]

#### **2. Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000**

In [45]:
q = '''SELECT EmployeeName,JobTitle, OvertimePay 
       FROM Salaries
       WHERE OvertimePay > 50000
       ORDER BY OvertimePay '''

sql_query(q)

            EmployeeName                        JobTitle   OvertimePay
0          Alan L Harvey                     Firefighter      50018.08
1               SARA COE                     FIREFIGHTER      50019.79
2     Michael I Thompson  Battalion Chief, Fire Suppress      50039.97
3            Craig F Tom                      Sergeant 3      50055.88
4        Nicholas Donati                Police Officer 3       50060.8
...                  ...                             ...           ...
2163      Gary Altenberg    Lieutenant, Fire Suppression     220909.48
2164        Not provided                    Not provided  Not Provided
2165        Not provided                    Not provided  Not Provided
2166        Not provided                    Not provided  Not Provided
2167        Not provided                    Not provided  Not Provided

[2168 rows x 3 columns]

#### **3. What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [43]:
q = '''SELECT COUNT(DISTINCT EmployeeName) as UniqueEmployees 
       FROM Salaries
       WHERE EmployeeName != "Not Provided"  
       AND EmployeeName != "Not provided"'''

sql_query(q)

   UniqueEmployees
0           110808

#### **4.Show The Top 10 highest Paid Employees**

In [33]:
q = '''SELECT EmployeeName, TotalPay 
       FROM Salaries
       ORDER BY TotalPay DESC
       LIMIT 10'''

sql_query(q)

           EmployeeName    TotalPay
0        NATHANIEL FORD  9999999.00
1           David Shinn   471952.64
2            Amy P Hart   390111.98
3        Gary Altenberg   362844.66
4         John Goldberg   350403.41
5           Samson  Lai   347102.32
6       Ellen G Moffatt   344187.46
7  William J Coaker Jr.   339653.70
8        Gregory P Suhr   339282.07
9     Frederick Binkley   337204.86

#### **5.Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [32]:
q= '''select EmployeeName, TotalPayBenefits FROM Salaries 
ORDER BY TotalPayBenefits DESC'''
sql_query(q)

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
1                David Shinn         510732.68
2                 Amy P Hart         479652.21
3       William J Coaker Jr.         436224.36
4             Gregory P Suhr         425815.28
...                      ...               ...
148648          Not provided              0.00
148649      Timothy E Gibson             -2.73
148650        Mark E Laherty             -8.20
148651         David P Kucia            -33.89
148652             Joe Lopez           -618.13

[148653 rows x 2 columns]